services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.21
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  spark:
    image: bitnami/spark:3.5.1
    environment:
      - SPARK_MODE=master
    expose:
      - "7077"
    ports:
      - "8080:8080"

  spark-worker:
    image: bitnami/spark:3.5.1
    depends_on:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1

  spark-submit:
    image: sparkprocessor
    build:
      context: ./SparkProcessor
      dockerfile: Dockerfile
    environment:
      - MASTER=spark://spark:7077
      - PACKAGES=org.apache.spark:spark-streaming-kafka-0-8-assembly_2.11:2.4.6
