services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_HOST}
      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  spark:
    image: bitnami/spark:3.2.4
    environment:
      - SPARK_MODE=master
    expose:
      - "7077"
    ports:
      - "8080:8080"

  spark-worker:
    image: bitnami/spark:3.2.4
    depends_on:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=${SPARK_MASTER}
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1

  spark-submit:
    image: sparkprocessor
    build:
      context: tenantstreamapp
      dockerfile: Dockerfile
    environment:
      - MASTER=${SPARK_MASTER}
      - KAFKA=kafka:9092
      - ZOOKEEPER=${ZOOKEEPER}
      - KAFKA_TOPIC=${KAFKA_TOPIC}

  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_DATABASE=coredms

    volumes:
      - mongodb_data:/bitnami/mongodb

volumes:
  mongodb_data:

